//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopKeeper.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class message_Feedback {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal message_Feedback() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShopKeeper.Properties.message_Feedback", typeof(message_Feedback).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Subscription activation failed. Please try again later..
        /// </summary>
        public static string Account_Activation_Failed {
            get {
                return ResourceManager.GetString("Account_Activation_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Subscription is yet to be activated..
        /// </summary>
        public static string Account_Activation_Required {
            get {
                return ResourceManager.GetString("Account_Activation_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Store subscription has expired and you cannot continue with your transactions. Please renew your subscription..
        /// </summary>
        public static string Account_Expired {
            get {
                return ResourceManager.GetString("Account_Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Provide Account Group Name..
        /// </summary>
        public static string Account_Group_Name_Error {
            get {
                return ResourceManager.GetString("Account_Group_Name_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select a valid Account Group..
        /// </summary>
        public static string Account_Group_Selection_Error {
            get {
                return ResourceManager.GetString("Account_Group_Selection_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account could not be activated. Please try again or contact the Admin for help..
        /// </summary>
        public static string Activation_Failure {
            get {
                return ResourceManager.GetString("Activation_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account been successfully activated. Please Login in to your Store with your login Details..
        /// </summary>
        public static string Activation_Success {
            get {
                return ResourceManager.GetString("Activation_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Subscription Process was successful but your user account could not be created. You can do this later by providing your reference code at your Login Page..
        /// </summary>
        public static string Admin_Account_Creation_Failure {
            get {
                return ResourceManager.GetString("Admin_Account_Creation_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide Amount Due.
        /// </summary>
        public static string Amount_Due_Error {
            get {
                return ResourceManager.GetString("Amount_Due_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Provide Amount Paid.
        /// </summary>
        public static string Amount_Paid_Error {
            get {
                return ResourceManager.GetString("Amount_Paid_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide Item Amount.
        /// </summary>
        public static string Amount_Sold_Error {
            get {
                return ResourceManager.GetString("Amount_Sold_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide Bank full name..
        /// </summary>
        public static string Bank_Name_Error {
            get {
                return ResourceManager.GetString("Bank_Name_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide Bank Sort Code..
        /// </summary>
        public static string Bank_Sort_Code_Error {
            get {
                return ResourceManager.GetString("Bank_Sort_Code_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide Billing Cycle Code..
        /// </summary>
        public static string Billing_Cycle_Code_Error {
            get {
                return ResourceManager.GetString("Billing_Cycle_Code_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide Billing Cycle Duration..
        /// </summary>
        public static string Billing_Cycle_Duration_Error {
            get {
                return ResourceManager.GetString("Billing_Cycle_Duration_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide Billing Cycle name..
        /// </summary>
        public static string Billing_Cycle_Name_Error {
            get {
                return ResourceManager.GetString("Billing_Cycle_Name_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a Billing Cycle.
        /// </summary>
        public static string Billing_Cycle_Selection_Error {
            get {
                return ResourceManager.GetString("Billing_Cycle_Selection_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Item Cannot be Deleted..
        /// </summary>
        public static string Cannot_Delete {
            get {
                return ResourceManager.GetString("Cannot_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Provide Account Code..
        /// </summary>
        public static string Chart_Of_Account_Code_Error {
            get {
                return ResourceManager.GetString("Chart_Of_Account_Code_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Chart of Account..
        /// </summary>
        public static string Chart_Of_Account_Selection_Error {
            get {
                return ResourceManager.GetString("Chart_Of_Account_Selection_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Provide Account Type..
        /// </summary>
        public static string Chart_Of_Account_Type_Error {
            get {
                return ResourceManager.GetString("Chart_Of_Account_Type_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide Menu Link.
        /// </summary>
        public static string ChildMenu_Href_Error {
            get {
                return ResourceManager.GetString("ChildMenu_Href_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide Menu Order.
        /// </summary>
        public static string ChildMenu_Order_Error {
            get {
                return ResourceManager.GetString("ChildMenu_Order_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide at least one role to access the menu.
        /// </summary>
        public static string ChildMenu_Roles_Error {
            get {
                return ResourceManager.GetString("ChildMenu_Roles_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide Menu Display Text.
        /// </summary>
        public static string ChildMenu_Value_Error {
            get {
                return ResourceManager.GetString("ChildMenu_Value_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide City name..
        /// </summary>
        public static string City_Name_Error {
            get {
                return ResourceManager.GetString("City_Name_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a valid City..
        /// </summary>
        public static string City_Selection_Error {
            get {
                return ResourceManager.GetString("City_Selection_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name  has been taken.
        /// </summary>
        public static string company_Name_Duplicate {
            get {
                return ResourceManager.GetString("company_Name_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide Product&apos;s Cost Price.
        /// </summary>
        public static string Cost_Price_In_Stock_Error {
            get {
                return ResourceManager.GetString("Cost_Price_In_Stock_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide Country name..
        /// </summary>
        public static string Country_Name_Error {
            get {
                return ResourceManager.GetString("Country_Name_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a Country..
        /// </summary>
        public static string Country_Selection_Error {
            get {
                return ResourceManager.GetString("Country_Selection_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide Coupon Code.
        /// </summary>
        public static string Coupon_Code_Error {
            get {
                return ResourceManager.GetString("Coupon_Code_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide Minimum Order Amount..
        /// </summary>
        public static string Coupon_Minimum_Order_Amount_Error {
            get {
                return ResourceManager.GetString("Coupon_Minimum_Order_Amount_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide Percentage Deduction.
        /// </summary>
        public static string Coupon_Percentage_Deduction_Error {
            get {
                return ResourceManager.GetString("Coupon_Percentage_Deduction_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide Coupon Title..
        /// </summary>
        public static string Coupon_Title_Error {
            get {
                return ResourceManager.GetString("Coupon_Title_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Provide Coupon Validity Start Date.
        /// </summary>
        public static string Coupon_Valid_From_Error {
            get {
                return ResourceManager.GetString("Coupon_Valid_From_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupon Validity Start Date Must not be Earlier than Today.
        /// </summary>
        public static string Coupon_Valid_From_Less_Error {
            get {
                return ResourceManager.GetString("Coupon_Valid_From_Less_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide Coupon Validity End Date.
        /// </summary>
        public static string Coupon_Valid_To_Error {
            get {
                return ResourceManager.GetString("Coupon_Valid_To_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupon Validity Date Date Must not be Earlier than Today.
        /// </summary>
        public static string Coupon_Valid_To_Less_Error {
            get {
                return ResourceManager.GetString("Coupon_Valid_To_Less_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupon Validity Start Date must not be later than the Validity End Date..
        /// </summary>
        public static string Coupon_Validity_Error {
            get {
                return ResourceManager.GetString("Coupon_Validity_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide Currency name..
        /// </summary>
        public static string Currency_Name_Error {
            get {
                return ResourceManager.GetString("Currency_Name_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide Currency Symbol..
        /// </summary>
        public static string Currency_Symbol_Error {
            get {
                return ResourceManager.GetString("Currency_Symbol_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide Customer&apos;s Address..
        /// </summary>
        public static string Customer_Address_Error {
            get {
                return ResourceManager.GetString("Customer_Address_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide an email fr commuicating with your customers.
        /// </summary>
        public static string Customer_Email_Empty {
            get {
                return ResourceManager.GetString("Customer_Email_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide Customer Type Code..
        /// </summary>
        public static string Customer_Type_Code {
            get {
                return ResourceManager.GetString("Customer_Type_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide Customer Type Name..
        /// </summary>
        public static string Customer_Type_Name {
            get {
                return ResourceManager.GetString("Customer_Type_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Customer Type.
        /// </summary>
        public static string Customer_Type_Selection_Error {
            get {
                return ResourceManager.GetString("Customer_Type_Selection_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide purchased item reception date.
        /// </summary>
        public static string Date_Delivered_Error {
            get {
                return ResourceManager.GetString("Date_Delivered_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Hired cannot be later than Today.
        /// </summary>
        public static string Date_Hired_Error {
            get {
                return ResourceManager.GetString("Date_Hired_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item information could not be deleted..
        /// </summary>
        public static string Delete_Failure {
            get {
                return ResourceManager.GetString("Delete_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item information was successfully deleted..
        /// </summary>
        public static string Delete_Success {
            get {
                return ResourceManager.GetString("Delete_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide Delivery Method Title..
        /// </summary>
        public static string Delivery_Method_Title_Error {
            get {
                return ResourceManager.GetString("Delivery_Method_Title_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide the Total cost for this order..
        /// </summary>
        public static string Derived_Total_Cost_Error {
            get {
                return ResourceManager.GetString("Derived_Total_Cost_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Email is already in use..
        /// </summary>
        public static string Duplicate_Email {
            get {
                return ResourceManager.GetString("Duplicate_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Mobile phone number is already in use..
        /// </summary>
        public static string Duplicate_Mobile_Number {
            get {
                return ResourceManager.GetString("Duplicate_Mobile_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Sort Code has been registered for another Bank..
        /// </summary>
        public static string Duplicate_Sort_Code {
            get {
                return ResourceManager.GetString("Duplicate_Sort_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An activation mail could not be sent to the provided Email address. Please go to the &apos;Request Activation Mail&apos; section on your Store login page to request for a new activation email..
        /// </summary>
        public static string Email_Failure {
            get {
                return ResourceManager.GetString("Email_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An activation mail has been sent to the provided Email address. Please click on the link provided in the mail to activate your account..
        /// </summary>
        public static string Email_Success {
            get {
                return ResourceManager.GetString("Email_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Address could not be Added.
        /// </summary>
        public static string Employee_Address_Add_Error {
            get {
                return ResourceManager.GetString("Employee_Address_Add_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide Employee&apos;s Address.
        /// </summary>
        public static string Employee_Address_Error {
            get {
                return ResourceManager.GetString("Employee_Address_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Address could not be updated.
        /// </summary>
        public static string Employee_Address_Update_Error {
            get {
                return ResourceManager.GetString("Employee_Address_Update_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide Employee&apos;s Number.
        /// </summary>
        public static string Employee_No_Error {
            get {
                return ResourceManager.GetString("Employee_No_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide Email.
        /// </summary>
        public static string Empty_Email {
            get {
                return ResourceManager.GetString("Empty_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a User Name for your Account.
        /// </summary>
        public static string Empty_User_Name {
            get {
                return ResourceManager.GetString("Empty_User_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select at least one estimate item..
        /// </summary>
        public static string Estimate_Items_Error {
            get {
                return ResourceManager.GetString("Estimate_Items_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide expected delivery date.
        /// </summary>
        public static string Expected_Delivery_Date_Error {
            get {
                return ResourceManager.GetString("Expected_Delivery_Date_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A fatal error was encountered. Please try again..
        /// </summary>
        public static string Fatal_Error {
            get {
                return ResourceManager.GetString("Fatal_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Image View Collection could not be processed.
        /// </summary>
        public static string File_Collection_Error {
            get {
                return ResourceManager.GetString("File_Collection_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Information could not be processed.
        /// </summary>
        public static string File_Error {
            get {
                return ResourceManager.GetString("File_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File could not be Saved.
        /// </summary>
        public static string File_Upload_Error {
            get {
                return ResourceManager.GetString("File_Upload_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer&apos;s purchase Date tis not invalid..
        /// </summary>
        public static string First_Purchase_Date_Eror {
            get {
                return ResourceManager.GetString("First_Purchase_Date_Eror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an Image View.
        /// </summary>
        public static string Image_View_Error {
            get {
                return ResourceManager.GetString("Image_View_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide Image View Name..
        /// </summary>
        public static string ImageView_Name_Error {
            get {
                return ResourceManager.GetString("ImageView_Name_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item could not be added. Please try again..
        /// </summary>
        public static string Insertion_Failure {
            get {
                return ResourceManager.GetString("Insertion_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item information was successfully added.
        /// </summary>
        public static string Insertion_Success {
            get {
                return ResourceManager.GetString("Insertion_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password..
        /// </summary>
        public static string Invalid_Credentials {
            get {
                return ResourceManager.GetString("Invalid_Credentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a valid Expiry Date.
        /// </summary>
        public static string Invalid_Expiry_Date {
            get {
                return ResourceManager.GetString("Invalid_Expiry_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid File.
        /// </summary>
        public static string Invalid_File {
            get {
                return ResourceManager.GetString("Invalid_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid selection!.
        /// </summary>
        public static string Invalid_Selection {
            get {
                return ResourceManager.GetString("Invalid_Selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Value for Subscription Payment.
        /// </summary>
        public static string Invalid_Subscription_Price {
            get {
                return ResourceManager.GetString("Invalid_Subscription_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory List is empty.
        /// </summary>
        public static string Inventory_List_Empty {
            get {
                return ResourceManager.GetString("Inventory_List_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A similar item already exists..
        /// </summary>
        public static string Item_Duplicate {
            get {
                return ResourceManager.GetString("Item_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a Role.
        /// </summary>
        public static string JobRole_Selection_Error {
            get {
                return ResourceManager.GetString("JobRole_Selection_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested Item list could not be retrieved..
        /// </summary>
        public static string List_Read_Failure {
            get {
                return ResourceManager.GetString("List_Read_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Store Information could not be retrived. Please try again or contact an agent..
        /// </summary>
        public static string Login_Failed {
            get {
                return ResourceManager.GetString("Login_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu List is empty.
        /// </summary>
        public static string Menu_List_Empty {
            get {
                return ResourceManager.GetString("Menu_List_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide minimum Quantity.
        /// </summary>
        public static string Min_Quantity_Error {
            get {
                return ResourceManager.GetString("Min_Quantity_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a Password of at least 8 character lenght.
        /// </summary>
        public static string Minimum_Password_Lenght {
            get {
                return ResourceManager.GetString("Minimum_Password_Lenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide all required field(s) and try again..
        /// </summary>
        public static string Model_State_Error {
            get {
                return ResourceManager.GetString("Model_State_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process was successful..
        /// </summary>
        public static string Offline_Activation_Success {
            get {
                return ResourceManager.GetString("Offline_Activation_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Outlet Address could not be added. Please try again.
        /// </summary>
        public static string Outlet_Address_Error {
            get {
                return ResourceManager.GetString("Outlet_Address_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Provide Outlet Address.
        /// </summary>
        public static string Outlet_Address_Not_Provided {
            get {
                return ResourceManager.GetString("Outlet_Address_Not_Provided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Provide Outlet Name.
        /// </summary>
        public static string Outlet_Name_Eror {
            get {
                return ResourceManager.GetString("Outlet_Name_Eror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an Outlet.
        /// </summary>
        public static string Outlet_Selection_Error {
            get {
                return ResourceManager.GetString("Outlet_Selection_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Parent Menu.
        /// </summary>
        public static string ParentMenu_Error {
            get {
                return ResourceManager.GetString("ParentMenu_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide Menu Link.
        /// </summary>
        public static string ParentMenu_Href_Error {
            get {
                return ResourceManager.GetString("ParentMenu_Href_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide Menu Order.
        /// </summary>
        public static string ParentMenu_Order_Error {
            get {
                return ResourceManager.GetString("ParentMenu_Order_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide at least one role to access the menu.
        /// </summary>
        public static string ParentMenu_Roles_Error {
            get {
                return ResourceManager.GetString("ParentMenu_Roles_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide Menu Display Text.
        /// </summary>
        public static string ParentMenu_Value_Error {
            get {
                return ResourceManager.GetString("ParentMenu_Value_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a Password for your Account.
        /// </summary>
        public static string Password_Empty {
            get {
                return ResourceManager.GetString("Password_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide Payment Gateway Name..
        /// </summary>
        public static string Payment_Gateway_Error {
            get {
                return ResourceManager.GetString("Payment_Gateway_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Payment Method..
        /// </summary>
        public static string Payment_Method_Selection_Error {
            get {
                return ResourceManager.GetString("Payment_Method_Selection_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Payment Type.
        /// </summary>
        public static string Payment_Type_Selection_Error {
            get {
                return ResourceManager.GetString("Payment_Type_Selection_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide Product&apos;s Price.
        /// </summary>
        public static string Price_In_Stock_Error {
            get {
                return ResourceManager.GetString("Price_In_Stock_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to complete the the requested process. Please try later..
        /// </summary>
        public static string Process_Failed {
            get {
                return ResourceManager.GetString("Process_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide Product Brand Name..
        /// </summary>
        public static string Product_Brand_Name_Error {
            get {
                return ResourceManager.GetString("Product_Brand_Name_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Product Brand..
        /// </summary>
        public static string Product_Brand_Selection_Error {
            get {
                return ResourceManager.GetString("Product_Brand_Selection_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide Product Category name..
        /// </summary>
        public static string Product_Category_Name_Error {
            get {
                return ResourceManager.GetString("Product_Category_Name_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Product Category..
        /// </summary>
        public static string Product_Category_Selection_Error {
            get {
                return ResourceManager.GetString("Product_Category_Selection_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide Product name/model..
        /// </summary>
        public static string Product_Name_Error {
            get {
                return ResourceManager.GetString("Product_Name_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide Product Type name..
        /// </summary>
        public static string Product_Type_Name_Error {
            get {
                return ResourceManager.GetString("Product_Type_Name_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Product Type..
        /// </summary>
        public static string Product_Type_Selection_Error {
            get {
                return ResourceManager.GetString("Product_Type_Selection_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Stock Variant list is empty..
        /// </summary>
        public static string Product_Variant_List_Error {
            get {
                return ResourceManager.GetString("Product_Variant_List_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide Product Variation name..
        /// </summary>
        public static string Product_Variation_Name_Error {
            get {
                return ResourceManager.GetString("Product_Variation_Name_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Product Distinguishing Property.
        /// </summary>
        public static string Product_Variation_Selection_Error {
            get {
                return ResourceManager.GetString("Product_Variation_Selection_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide Product Variation Value name..
        /// </summary>
        public static string Product_Variation_Value_Name_Error {
            get {
                return ResourceManager.GetString("Product_Variation_Value_Name_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Product Distinguishing Value.
        /// </summary>
        public static string Product_Variation_Value_Selection_Error {
            get {
                return ResourceManager.GetString("Product_Variation_Value_Selection_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select at least one item to purchase..
        /// </summary>
        public static string Purchase_Order_Items_Error {
            get {
                return ResourceManager.GetString("Purchase_Order_Items_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide Quantity received.
        /// </summary>
        public static string Quantity_Delivered_Error {
            get {
                return ResourceManager.GetString("Quantity_Delivered_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide Quantity in Stock.
        /// </summary>
        public static string Quantity_In_Stock_Error {
            get {
                return ResourceManager.GetString("Quantity_In_Stock_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide Item Quantity.
        /// </summary>
        public static string Quantity_Sold_Error {
            get {
                return ResourceManager.GetString("Quantity_Sold_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item could not be retrieved..
        /// </summary>
        public static string Read_Failure {
            get {
                return ResourceManager.GetString("Read_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide Register Name.
        /// </summary>
        public static string Register_Name_Error {
            get {
                return ResourceManager.GetString("Register_Name_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale Payment infromation could not be processed.
        /// </summary>
        public static string Sale_Payment_List_Error {
            get {
                return ResourceManager.GetString("Sale_Payment_List_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide Salutation Name.
        /// </summary>
        public static string Salutation_Name_Error {
            get {
                return ResourceManager.GetString("Salutation_Name_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your session has timed out..
        /// </summary>
        public static string Session_Time_Out {
            get {
                return ResourceManager.GetString("Session_Time_Out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your sign up process was successfully completed, but your email could not be confirmed. Please request for an account activation link later..
        /// </summary>
        public static string Signup_Email_Confirmation_Failed {
            get {
                return ResourceManager.GetString("Signup_Email_Confirmation_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up failed..
        /// </summary>
        public static string SignUp_Failed {
            get {
                return ResourceManager.GetString("SignUp_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registeration was successfully completed. Please login with your credentials..
        /// </summary>
        public static string Signup_Successful {
            get {
                return ResourceManager.GetString("Signup_Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide Product&apos;s SKU .
        /// </summary>
        public static string SKU_Error {
            get {
                return ResourceManager.GetString("SKU_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Sold Item(s) information could not be processed.
        /// </summary>
        public static string Sold_Item_List_Error {
            get {
                return ResourceManager.GetString("Sold_Item_List_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide State name..
        /// </summary>
        public static string State_Name_Error {
            get {
                return ResourceManager.GetString("State_Name_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a State..
        /// </summary>
        public static string State_Selection_Error {
            get {
                return ResourceManager.GetString("State_Selection_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide Address..
        /// </summary>
        public static string Store_Address_StreetNo_Error {
            get {
                return ResourceManager.GetString("Store_Address_StreetNo_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a Product.
        /// </summary>
        public static string Store_Item_Selection_Error {
            get {
                return ResourceManager.GetString("Store_Item_Selection_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an Inventory.
        /// </summary>
        public static string Store_Item_Stock_Selection_Error {
            get {
                return ResourceManager.GetString("Store_Item_Stock_Selection_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide your Store Name.
        /// </summary>
        public static string Store_Name_Error_1 {
            get {
                return ResourceManager.GetString("Store_Name_Error_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Store Name has been taken..
        /// </summary>
        public static string Store_Name_Error_2 {
            get {
                return ResourceManager.GetString("Store_Name_Error_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an Outlet..
        /// </summary>
        public static string Store_Outlet_Selection_Eror {
            get {
                return ResourceManager.GetString("Store_Outlet_Selection_Eror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide Customer&apos;s Street number..
        /// </summary>
        public static string Street_Number_Error {
            get {
                return ResourceManager.GetString("Street_Number_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide Subscription Package File Storage Space..
        /// </summary>
        public static string Sub_Package_File_Storage_Error {
            get {
                return ResourceManager.GetString("Sub_Package_File_Storage_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide the Maximum Transactions for the Subscription Package..
        /// </summary>
        public static string Sub_Package_Max_Transaction_Error {
            get {
                return ResourceManager.GetString("Sub_Package_Max_Transaction_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide SubscriptionPackage name..
        /// </summary>
        public static string Sub_Package_Name_Error {
            get {
                return ResourceManager.GetString("Sub_Package_Name_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide the Number of Outlets for this Subscription Package..
        /// </summary>
        public static string Sub_Package_Number_of_Outlet_Error {
            get {
                return ResourceManager.GetString("Sub_Package_Number_of_Outlet_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide  the number of Store Products for this  Subscription Package..
        /// </summary>
        public static string Sub_Package_Number_of_Product_Error {
            get {
                return ResourceManager.GetString("Sub_Package_Number_of_Product_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide the Number of Registers for the Subscription Package..
        /// </summary>
        public static string Sub_Package_Number_of_Registers_Error {
            get {
                return ResourceManager.GetString("Sub_Package_Number_of_Registers_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide the applicable Number of Users for the Subscription Package..
        /// </summary>
        public static string Sub_Package_Number_of_Users_Error {
            get {
                return ResourceManager.GetString("Sub_Package_Number_of_Users_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The subscription Price could not be computed. Please try again later..
        /// </summary>
        public static string Subscription_Amount_Error {
            get {
                return ResourceManager.GetString("Subscription_Amount_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Subscription duration.
        /// </summary>
        public static string Subscription_Duration_Error {
            get {
                return ResourceManager.GetString("Subscription_Duration_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Subscription process failed. Please try again later..
        /// </summary>
        public static string Subscription_Failure {
            get {
                return ResourceManager.GetString("Subscription_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Subscription was successful. Please click on the &apos;Pay Now&apos; button presented below for payment using your subscription information presented below. Thanks..
        /// </summary>
        public static string Subscription_Success {
            get {
                return ResourceManager.GetString("Subscription_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Subscription was successful. An activation Email has been sent to the provided Email address. Please click on the provided link in the Email to activate your account..
        /// </summary>
        public static string Subscription_Success_1 {
            get {
                return ResourceManager.GetString("Subscription_Success_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Subscription was successful. Please walk into any of the approved Banks with a printed copy of your Payment slip presented below for payment. Thanks..
        /// </summary>
        public static string Subscription_Success_2 {
            get {
                return ResourceManager.GetString("Subscription_Success_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Subscription was successful. Please click on the &apos;Pay Now&apos; button presented below for payment using your subscription information presented below. Thanks..
        /// </summary>
        public static string Subscription_Success_3 {
            get {
                return ResourceManager.GetString("Subscription_Success_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide Supplier name..
        /// </summary>
        public static string Supplier_Name_Error {
            get {
                return ResourceManager.GetString("Supplier_Name_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a Supplier..
        /// </summary>
        public static string Supplier_Selection_Error {
            get {
                return ResourceManager.GetString("Supplier_Selection_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please it&apos;s strongly recommended tha you connect online to run updates on your system..
        /// </summary>
        public static string Tm_Lps_Error {
            get {
                return ResourceManager.GetString("Tm_Lps_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide Transaction Amount..
        /// </summary>
        public static string Transaction_Amount_Eror {
            get {
                return ResourceManager.GetString("Transaction_Amount_Eror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested action could not be completed.
        /// </summary>
        public static string Transaction_List_Error {
            get {
                return ResourceManager.GetString("Transaction_List_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide the Action for this Transaction Type..
        /// </summary>
        public static string Transaction_Type_Action_Error {
            get {
                return ResourceManager.GetString("Transaction_Type_Action_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide Transaction Type name..
        /// </summary>
        public static string Transaction_Type_Name_Error {
            get {
                return ResourceManager.GetString("Transaction_Type_Name_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Transaction Type..
        /// </summary>
        public static string Transaction_Type_Selection_Error {
            get {
                return ResourceManager.GetString("Transaction_Type_Selection_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error was encoutered and the Login operation was aborted. Please contact an agent if error persists..
        /// </summary>
        public static string Unknown_Login_Error {
            get {
                return ResourceManager.GetString("Unknown_Login_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide Unit of Measurement name..
        /// </summary>
        public static string UoM_Name_Error {
            get {
                return ResourceManager.GetString("UoM_Name_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Unit of Measurement.
        /// </summary>
        public static string UoM_Selection_Error {
            get {
                return ResourceManager.GetString("UoM_Selection_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item could not be updated. Please try again..
        /// </summary>
        public static string Update_Failure {
            get {
                return ResourceManager.GetString("Update_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Inventory Information was successfully updated, but the View Images could not be processed. Please try again.
        /// </summary>
        public static string Update_Session_Time_Out_With_Success {
            get {
                return ResourceManager.GetString("Update_Session_Time_Out_With_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item information was successfully updated..
        /// </summary>
        public static string Update_Success {
            get {
                return ResourceManager.GetString("Update_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User verification failed..
        /// </summary>
        public static string User_Not_Verified {
            get {
                return ResourceManager.GetString("User_Not_Verified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User was successfully Verified..
        /// </summary>
        public static string User_Verified {
            get {
                return ResourceManager.GetString("User_Verified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Gender.
        /// </summary>
        public static string UserProfile_Gender_Error {
            get {
                return ResourceManager.GetString("UserProfile_Gender_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide Last Name.
        /// </summary>
        public static string UserProfile_Last_Name_Error {
            get {
                return ResourceManager.GetString("UserProfile_Last_Name_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide customer&apos;s mobile phone number..
        /// </summary>
        public static string UserProfile_Mobile_Number {
            get {
                return ResourceManager.GetString("UserProfile_Mobile_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide Other Names..
        /// </summary>
        public static string UserProfile_Other_Names_Error {
            get {
                return ResourceManager.GetString("UserProfile_Other_Names_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide Satutation..
        /// </summary>
        public static string UserProfile_Salutation_Error {
            get {
                return ResourceManager.GetString("UserProfile_Salutation_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select UserProfile.
        /// </summary>
        public static string UserProfile_Selection_Eror {
            get {
                return ResourceManager.GetString("UserProfile_Selection_Eror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation failed. Please try again..
        /// </summary>
        public static string Validation_Failed {
            get {
                return ResourceManager.GetString("Validation_Failed", resourceCulture);
            }
        }
    }
}
