//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopKeeper.Master.EF.Models.Master
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactTag
    {
        public ContactTag()
        {
            this.StoreContacts = new HashSet<StoreContact>();
        }
    
        public int ContactTagId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<StoreContact> StoreContacts { get; set; }
    }
}
