//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopKeeper.Master.EF.Models.Master
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public Country()
        {
            this.Currencies = new HashSet<Currency>();
            this.States = new HashSet<State>();
        }
    
        public long CountryId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Currency> Currencies { get; set; }
        public virtual ICollection<State> States { get; set; }
    }
}
