//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopKeeper.Master.EF.Models.Master
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public long Id { get; set; }
        public long UserId { get; set; }
        public int MessageTemplateId { get; set; }
        public int Status { get; set; }
        public System.DateTime DateSent { get; set; }
        public string MessageBody { get; set; }
    
        public virtual MessageTemplate MessageTemplate { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
