//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopKeeper.Master.EF.Models.Master
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentGateway
    {
        public PaymentGateway()
        {
            this.StorePaymentGateways = new HashSet<StorePaymentGateway>();
        }
    
        public long PaymentGatewayId { get; set; }
        public string GatewayName { get; set; }
        public string LogoPath { get; set; }
    
        public virtual ICollection<StorePaymentGateway> StorePaymentGateways { get; set; }
    }
}
