//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopKeeper.Master.EF.Models.Master
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public Person()
        {
            this.StoreContacts = new HashSet<StoreContact>();
        }
    
        public long PersonId { get; set; }
        public string Salutation { get; set; }
        public string LastName { get; set; }
        public string OtherNames { get; set; }
        public string Gender { get; set; }
        public System.DateTime Birthday { get; set; }
        public string PhotofilePath { get; set; }
        public System.DateTime DateRegistered { get; set; }
    
        public virtual ICollection<StoreContact> StoreContacts { get; set; }
    }
}
