//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopKeeper.Master.EF.Models.Master
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ShopKeeperMasterEntities : DbContext
    {
        public ShopKeeperMasterEntities()
            : base("name=ShopKeeperMasterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<ActiveSubscription> ActiveSubscriptions { get; set; }
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<AlaCarte> AlaCartes { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Bank> Banks { get; set; }
        public virtual DbSet<BillingCycle> BillingCycles { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<ContactTag> ContactTags { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Currency> Currencies { get; set; }
        public virtual DbSet<Message> Messages { get; set; }
        public virtual DbSet<MessageTemplate> MessageTemplates { get; set; }
        public virtual DbSet<PackagePricing> PackagePricings { get; set; }
        public virtual DbSet<PaymentGateway> PaymentGateways { get; set; }
        public virtual DbSet<PaymentMethod> PaymentMethods { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<Store> Stores { get; set; }
        public virtual DbSet<StoreBankAccount> StoreBankAccounts { get; set; }
        public virtual DbSet<StoreContact> StoreContacts { get; set; }
        public virtual DbSet<StorePaymentGateway> StorePaymentGateways { get; set; }
        public virtual DbSet<StoreSetting> StoreSettings { get; set; }
        public virtual DbSet<StoreSubscriptionHistory> StoreSubscriptionHistories { get; set; }
        public virtual DbSet<SubscriptionPackage> SubscriptionPackages { get; set; }
        public virtual DbSet<Transaction> Transactions { get; set; }
        public virtual DbSet<TransactionType> TransactionTypes { get; set; }
        public virtual DbSet<UserProfile> UserProfiles { get; set; }
    }
}
