//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopKeeper.Master.EF.Models.Master
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store
    {
        public Store()
        {
            this.ActiveSubscriptions = new HashSet<ActiveSubscription>();
            this.StoreBankAccounts = new HashSet<StoreBankAccount>();
            this.StorePaymentGateways = new HashSet<StorePaymentGateway>();
            this.StoreSubscriptionHistories = new HashSet<StoreSubscriptionHistory>();
        }
    
        public long StoreId { get; set; }
        public string StoreName { get; set; }
        public int TotalOutlets { get; set; }
        public string StoreAlias { get; set; }
        public string CompanyName { get; set; }
        public string CustomerEmail { get; set; }
        public int SubscriptionStatus { get; set; }
        public string BillingCycleCode { get; set; }
        public string StoreLogoPath { get; set; }
        public string DefaultCurrency { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public string SecreteKey { get; set; }
        public long SubscriptionPackageId { get; set; }
    
        public virtual ICollection<ActiveSubscription> ActiveSubscriptions { get; set; }
        public virtual SubscriptionPackage SubscriptionPackage { get; set; }
        public virtual ICollection<StoreBankAccount> StoreBankAccounts { get; set; }
        public virtual ICollection<StorePaymentGateway> StorePaymentGateways { get; set; }
        public virtual StoreSetting StoreSetting { get; set; }
        public virtual ICollection<StoreSubscriptionHistory> StoreSubscriptionHistories { get; set; }
    }
}
