//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopKeeper.Master.EF.Models.Master
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreSetting
    {
        public long StoreId { get; set; }
        public string InitialCatalog { get; set; }
        public string StorePsswd { get; set; }
        public string DataSource { get; set; }
        public string UserName { get; set; }
    
        public virtual Store Store { get; set; }
    }
}
