//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopKeeper.Master.EF.Models.Master
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreBankAccount
    {
        public long StoreBankAccountId { get; set; }
        public long StoreId { get; set; }
        public long BankId { get; set; }
        public string AccountName { get; set; }
        public long AccountNo { get; set; }
        public bool Status { get; set; }
    
        public virtual Bank Bank { get; set; }
        public virtual Store Store { get; set; }
    }
}
