//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopKeeper.Master.EF.Models.Master
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreContact
    {
        public long StoreContactId { get; set; }
        public long PersonId { get; set; }
        public int ContactTagId { get; set; }
        public string Contact { get; set; }
        public System.DateTime LastUpdated { get; set; }
    
        public virtual ContactTag ContactTag { get; set; }
        public virtual Person Person { get; set; }
    }
}
