//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopKeeper.Master.EF.Models.Master
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreSubscriptionHistory
    {
        public long StoreSubscriptionHistoryId { get; set; }
        public long StoreId { get; set; }
        public long SubscriptionPackageId { get; set; }
        public Nullable<long> PaymentId { get; set; }
        public System.DateTime DateSubscribed { get; set; }
        public System.DateTime SubscriptionExpiryDate { get; set; }
        public int Duration { get; set; }
        public string Note { get; set; }
    
        public virtual Store Store { get; set; }
        public virtual SubscriptionPackage SubscriptionPackage { get; set; }
    }
}
