//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopKeeper.Master.EF.Models.Master
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public UserProfile()
        {
            this.AspNetUsers = new HashSet<AspNetUser>();
            this.Messages = new HashSet<Message>();
        }
    
        public long Id { get; set; }
        public Nullable<int> SalutationId { get; set; }
        public string LastName { get; set; }
        public string OtherNames { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string PhotofilePath { get; set; }
        public bool IsActive { get; set; }
        public string ContactEmail { get; set; }
        public string MobileNumber { get; set; }
        public string OfficeLine { get; set; }
    
        public virtual ICollection<AspNetUser> AspNetUsers { get; set; }
        public virtual ICollection<Message> Messages { get; set; }
    }
}
