//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopkeeperStore.EF.Models.Store
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountGroup
    {
        public AccountGroup()
        {
            this.ChartOfAccounts = new HashSet<ChartOfAccount>();
        }
    
        public int AccountGroupId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<ChartOfAccount> ChartOfAccounts { get; set; }
    }
}
