//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopkeeperStore.EF.Models.Store
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankAccount
    {
        public long BankAccountId { get; set; }
        public long BankId { get; set; }
        public string AccountName { get; set; }
        public long AccountNo { get; set; }
        public bool Status { get; set; }
        public long CustomerId { get; set; }
    
        public virtual StoreBank StoreBank { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
