//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopkeeperStore.EF.Models.Store
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coupon
    {
        public Coupon()
        {
            this.ShoppingCarts = new HashSet<ShoppingCart>();
            this.StoreOutletCoupons = new HashSet<StoreOutletCoupon>();
        }
    
        public long CouponId { get; set; }
        public string Code { get; set; }
        public double PercentageDeduction { get; set; }
        public System.DateTime ValidFrom { get; set; }
        public System.DateTime ValidTo { get; set; }
        public double MinimumOrderAmount { get; set; }
        public string Title { get; set; }
    
        public virtual ICollection<ShoppingCart> ShoppingCarts { get; set; }
        public virtual ICollection<StoreOutletCoupon> StoreOutletCoupons { get; set; }
    }
}
