//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopkeeperStore.EF.Models.Store
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.BankAccounts = new HashSet<BankAccount>();
            this.CustomerInvoices = new HashSet<CustomerInvoice>();
            this.DeliveryAddresses = new HashSet<DeliveryAddress>();
            this.Estimates = new HashSet<Estimate>();
            this.RefundNotes = new HashSet<RefundNote>();
            this.Sales = new HashSet<Sale>();
            this.ShoppingCarts = new HashSet<ShoppingCart>();
        }
    
        public long CustomerId { get; set; }
        public Nullable<long> ReferredByCustomerId { get; set; }
        public int StoreCustomerTypeId { get; set; }
        public Nullable<int> StoreOutletId { get; set; }
        public long UserId { get; set; }
        public Nullable<System.DateTime> FirstPurchaseDate { get; set; }
        public Nullable<long> ContactPersonId { get; set; }
        public Nullable<System.DateTime> DateProfiled { get; set; }
    
        public virtual ICollection<BankAccount> BankAccounts { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual UserProfile UserProfile { get; set; }
        public virtual StoreCustomerType StoreCustomerType { get; set; }
        public virtual StoreOutlet StoreOutlet { get; set; }
        public virtual ICollection<CustomerInvoice> CustomerInvoices { get; set; }
        public virtual ICollection<DeliveryAddress> DeliveryAddresses { get; set; }
        public virtual ICollection<Estimate> Estimates { get; set; }
        public virtual ICollection<RefundNote> RefundNotes { get; set; }
        public virtual ICollection<Sale> Sales { get; set; }
        public virtual ICollection<ShoppingCart> ShoppingCarts { get; set; }
    }
}
