//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopkeeperStore.EF.Models.Store
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerInvoice
    {
        public long Id { get; set; }
        public long CustomerId { get; set; }
        public double TotalAmountPaid { get; set; }
        public double TotalAmountDue { get; set; }
        public double InvoiceBalance { get; set; }
        public double TotalVATAmount { get; set; }
        public double TotalDiscountAmount { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
