//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopkeeperStore.EF.Models.Store
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailySale
    {
        public long DailySaleId { get; set; }
        public System.DateTime SalesDate { get; set; }
        public int StoreOutletId { get; set; }
        public double AmountSold { get; set; }
        public byte[] LastUpdated { get; set; }
    
        public virtual StoreOutlet StoreOutlet { get; set; }
    }
}
