//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopkeeperStore.EF.Models.Store
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryAddress
    {
        public DeliveryAddress()
        {
            this.ShoppingCarts = new HashSet<ShoppingCart>();
        }
    
        public long Id { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public long CityId { get; set; }
        public Nullable<long> CustomerId { get; set; }
        public string CustomerIpAddress { get; set; }
        public string ZipCode { get; set; }
        public string MobileNumber { get; set; }
        public string TelephoneNumber { get; set; }
        public string ContactEmail { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual StoreCity StoreCity { get; set; }
        public virtual ICollection<ShoppingCart> ShoppingCarts { get; set; }
    }
}
