//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopkeeperStore.EF.Models.Store
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.Customers = new HashSet<Customer>();
            this.EmployeeAssigments = new HashSet<EmployeeAssigment>();
            this.EmployeeDocuments = new HashSet<EmployeeDocument>();
            this.EmployeeSalesLogs = new HashSet<EmployeeSalesLog>();
            this.PurchaseOrders = new HashSet<PurchaseOrder>();
            this.PurchaseOrderItemDeliveries = new HashSet<PurchaseOrderItemDelivery>();
            this.RefundNotes = new HashSet<RefundNote>();
            this.Sales = new HashSet<Sale>();
            this.ShoppingCartDeliveries = new HashSet<ShoppingCartDelivery>();
            this.StoreTransactions = new HashSet<StoreTransaction>();
            this.WayBills = new HashSet<WayBill>();
            this.WayBills1 = new HashSet<WayBill>();
        }
    
        public long EmployeeId { get; set; }
        public long UserId { get; set; }
        public string EmployeeNo { get; set; }
        public System.DateTime DateHired { get; set; }
        public Nullable<System.DateTime> DateLeft { get; set; }
        public int StoreOutletId { get; set; }
        public long StoreAddressId { get; set; }
        public long StoreDepartmentId { get; set; }
        public int Status { get; set; }
    
        public virtual ICollection<Customer> Customers { get; set; }
        public virtual UserProfile UserProfile { get; set; }
        public virtual StoreDepartment StoreDepartment { get; set; }
        public virtual StoreOutlet StoreOutlet { get; set; }
        public virtual UserProfile UserProfile1 { get; set; }
        public virtual ICollection<EmployeeAssigment> EmployeeAssigments { get; set; }
        public virtual ICollection<EmployeeDocument> EmployeeDocuments { get; set; }
        public virtual ICollection<EmployeeSalesLog> EmployeeSalesLogs { get; set; }
        public virtual ICollection<PurchaseOrder> PurchaseOrders { get; set; }
        public virtual ICollection<PurchaseOrderItemDelivery> PurchaseOrderItemDeliveries { get; set; }
        public virtual ICollection<RefundNote> RefundNotes { get; set; }
        public virtual ICollection<Sale> Sales { get; set; }
        public virtual ICollection<ShoppingCartDelivery> ShoppingCartDeliveries { get; set; }
        public virtual ICollection<StoreTransaction> StoreTransactions { get; set; }
        public virtual ICollection<WayBill> WayBills { get; set; }
        public virtual ICollection<WayBill> WayBills1 { get; set; }
    }
}
