//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopkeeperStore.EF.Models.Store
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeDocument
    {
        public long EmployeeDocumentId { get; set; }
        public long EmployeeId { get; set; }
        public int DocumentTypeId { get; set; }
        public string FilePath { get; set; }
        public byte[] DateAttached { get; set; }
    
        public virtual DocumentType DocumentType { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
