//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopkeeperStore.EF.Models.Store
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estimate
    {
        public Estimate()
        {
            this.EstimateItems = new HashSet<EstimateItem>();
        }
    
        public long Id { get; set; }
        public bool ConvertedToInvoice { get; set; }
        public string EstimateNumber { get; set; }
        public long CreatedById { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateConverted { get; set; }
        public double VAT { get; set; }
        public double Discount { get; set; }
        public long CustomerId { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public int OutletId { get; set; }
        public double AmountDue { get; set; }
        public double NetAmount { get; set; }
        public double VATAmount { get; set; }
        public double DiscountAmount { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual StoreOutlet StoreOutlet { get; set; }
        public virtual UserProfile UserProfile { get; set; }
        public virtual ICollection<EstimateItem> EstimateItems { get; set; }
    }
}
