//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopkeeperStore.EF.Models.Store
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceRequestItem
    {
        public long Id { get; set; }
        public long StoreItemSoldId { get; set; }
        public long InvoiceRequestId { get; set; }
        public double QuantityDispatched { get; set; }
        public System.DateTime DateDispatched { get; set; }
    
        public virtual InvoiceRequest InvoiceRequest { get; set; }
        public virtual StoreItemSold StoreItemSold { get; set; }
    }
}
