//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopkeeperStore.EF.Models.Store
{
    using System;
    using System.Collections.Generic;
    
    public partial class IssueType
    {
        public IssueType()
        {
            this.RefundNotes = new HashSet<RefundNote>();
            this.ReturnedProducts = new HashSet<ReturnedProduct>();
            this.StoreItemIssues = new HashSet<StoreItemIssue>();
        }
    
        public int IssueTypeId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<RefundNote> RefundNotes { get; set; }
        public virtual ICollection<ReturnedProduct> ReturnedProducts { get; set; }
        public virtual ICollection<StoreItemIssue> StoreItemIssues { get; set; }
    }
}
