//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopkeeperStore.EF.Models.Store
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobRole
    {
        public JobRole()
        {
            this.EmployeeAssigments = new HashSet<EmployeeAssigment>();
        }
    
        public long JobRoleId { get; set; }
        public string JobTitle { get; set; }
        public string JobDescription { get; set; }
        public string Responsibilities { get; set; }
        public string MinQualification { get; set; }
    
        public virtual ICollection<EmployeeAssigment> EmployeeAssigments { get; set; }
    }
}
