//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopkeeperStore.EF.Models.Store
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParentMenu
    {
        public ParentMenu()
        {
            this.ChildMenus = new HashSet<ChildMenu>();
            this.ParentMenuRoles = new HashSet<ParentMenuRole>();
        }
    
        public int ParentMenuId { get; set; }
        public string Value { get; set; }
        public string Href { get; set; }
        public int MenuOrder { get; set; }
        public string GlyphIconClass { get; set; }
    
        public virtual ICollection<ChildMenu> ChildMenus { get; set; }
        public virtual ICollection<ParentMenuRole> ParentMenuRoles { get; set; }
    }
}
