//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopkeeperStore.EF.Models.Store
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonContact
    {
        public long PersonContactId { get; set; }
        public long UserId { get; set; }
        public int ContactTypeId { get; set; }
        public string ContactValue { get; set; }
        public bool IsDefault { get; set; }
        public string ContactTagName { get; set; }
    
        public virtual ContactType ContactType { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
