//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopkeeperStore.EF.Models.Store
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrderPayment
    {
        public long PurchaseOrderPaymentId { get; set; }
        public long StoreTransactionId { get; set; }
        public long PurchaseOrderId { get; set; }
        public Nullable<double> AmountPaid { get; set; }
        public System.DateTime DateMade { get; set; }
        public string InvoiceFilePath { get; set; }
        public string Remark { get; set; }
    
        public virtual PurchaseOrder PurchaseOrder { get; set; }
        public virtual StoreTransaction StoreTransaction { get; set; }
    }
}
