//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopkeeperStore.EF.Models.Store
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrderItemDelivery
    {
        public long PurchaseOrderItemDeliveryId { get; set; }
        public long PurchaseOrderItemId { get; set; }
        public double QuantityDelivered { get; set; }
        public System.DateTime DateDelivered { get; set; }
        public long ReceivedById { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual PurchaseOrderItem PurchaseOrderItem { get; set; }
    }
}
