//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopkeeperStore.EF.Models.Store
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrder
    {
        public PurchaseOrder()
        {
            this.Invoices = new HashSet<Invoice>();
            this.PurchaseOrderItems = new HashSet<PurchaseOrderItem>();
            this.PurchaseOrderPayments = new HashSet<PurchaseOrderPayment>();
        }
    
        public long PurchaseOrderId { get; set; }
        public int StoreOutletId { get; set; }
        public int AccountId { get; set; }
        public long SupplierId { get; set; }
        public int StatusCode { get; set; }
        public System.DateTime DateTimePlaced { get; set; }
        public Nullable<double> DerivedTotalCost { get; set; }
        public long GeneratedById { get; set; }
        public System.DateTime ExpectedDeliveryDate { get; set; }
        public Nullable<System.DateTime> ActualDeliveryDate { get; set; }
        public string PurchaseOrderNumber { get; set; }
        public double VATAmount { get; set; }
        public double DiscountAmount { get; set; }
        public double FOB { get; set; }
    
        public virtual ChartOfAccount ChartOfAccount { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual ICollection<Invoice> Invoices { get; set; }
        public virtual StoreOutlet StoreOutlet { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual ICollection<PurchaseOrderItem> PurchaseOrderItems { get; set; }
        public virtual ICollection<PurchaseOrderPayment> PurchaseOrderPayments { get; set; }
    }
}
