//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopkeeperStore.EF.Models.Store
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrderItem
    {
        public PurchaseOrderItem()
        {
            this.PurchaseOrderItemDeliveries = new HashSet<PurchaseOrderItemDelivery>();
        }
    
        public long PurchaseOrderItemId { get; set; }
        public long PurchaseOrderId { get; set; }
        public long StoreItemStockId { get; set; }
        public string SerialNumber { get; set; }
        public double QuantityOrdered { get; set; }
        public double QuantityDelivered { get; set; }
        public int StatusCode { get; set; }
        public double CostPrice { get; set; }
        public double QuantityInStock { get; set; }
    
        public virtual PurchaseOrder PurchaseOrder { get; set; }
        public virtual StoreItemStock StoreItemStock { get; set; }
        public virtual ICollection<PurchaseOrderItemDelivery> PurchaseOrderItemDeliveries { get; set; }
    }
}
