//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopkeeperStore.EF.Models.Store
{
    using System;
    using System.Collections.Generic;
    
    public partial class RefundNote
    {
        public RefundNote()
        {
            this.ReturnedProducts = new HashSet<ReturnedProduct>();
        }
    
        public long Id { get; set; }
        public long SaleId { get; set; }
        public double Discount { get; set; }
        public double DiscountAmount { get; set; }
        public double VAT { get; set; }
        public double VATAmount { get; set; }
        public int PaymentMethodId { get; set; }
        public System.DateTime DateReturned { get; set; }
        public double AmountDue { get; set; }
        public double NetAmount { get; set; }
        public Nullable<int> IssueTypeId { get; set; }
        public long EmployeeId { get; set; }
        public long CustomerId { get; set; }
        public string RefundNoteNumber { get; set; }
        public long TransactionId { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual IssueType IssueType { get; set; }
        public virtual Sale Sale { get; set; }
        public virtual StorePaymentMethod StorePaymentMethod { get; set; }
        public virtual StoreTransaction StoreTransaction { get; set; }
        public virtual ICollection<ReturnedProduct> ReturnedProducts { get; set; }
    }
}
