//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopkeeperStore.EF.Models.Store
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReturnedProduct
    {
        public long ReturnedProductId { get; set; }
        public int IssueTypeId { get; set; }
        public long StoreItemStockId { get; set; }
        public long RefundNoteId { get; set; }
        public System.DateTime DateReturned { get; set; }
        public double QuantityBought { get; set; }
        public double QuantityReturned { get; set; }
        public double AmountRefunded { get; set; }
        public double Rate { get; set; }
    
        public virtual IssueType IssueType { get; set; }
        public virtual RefundNote RefundNote { get; set; }
        public virtual StoreItemStock StoreItemStock { get; set; }
    }
}
