//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopkeeperStore.EF.Models.Store
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public Sale()
        {
            this.InvoiceRequests = new HashSet<InvoiceRequest>();
            this.RefundNotes = new HashSet<RefundNote>();
            this.SalePayments = new HashSet<SalePayment>();
            this.SaleTransactions = new HashSet<SaleTransaction>();
            this.StoreItemSolds = new HashSet<StoreItemSold>();
        }
    
        public long SaleId { get; set; }
        public double AmountDue { get; set; }
        public int Status { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> RegisterId { get; set; }
        public long EmployeeId { get; set; }
        public Nullable<long> CustomerId { get; set; }
        public double Discount { get; set; }
        public double VAT { get; set; }
        public double NetAmount { get; set; }
        public string InvoiceNumber { get; set; }
        public double VATAmount { get; set; }
        public double DiscountAmount { get; set; }
        public string EstimateNumber { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual ICollection<InvoiceRequest> InvoiceRequests { get; set; }
        public virtual ICollection<RefundNote> RefundNotes { get; set; }
        public virtual Register Register { get; set; }
        public virtual ICollection<SalePayment> SalePayments { get; set; }
        public virtual ICollection<SaleTransaction> SaleTransactions { get; set; }
        public virtual ICollection<StoreItemSold> StoreItemSolds { get; set; }
    }
}
