//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopkeeperStore.EF.Models.Store
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalePayment
    {
        public long SalePaymentId { get; set; }
        public long SaleId { get; set; }
        public double AmountPaid { get; set; }
        public System.DateTime DatePaid { get; set; }
    
        public virtual Sale Sale { get; set; }
    }
}
