//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopkeeperStore.EF.Models.Store
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleTransaction
    {
        public long SaleTransactionId { get; set; }
        public long SaleId { get; set; }
        public long StoreTransactionId { get; set; }
    
        public virtual Sale Sale { get; set; }
        public virtual StoreTransaction StoreTransaction { get; set; }
    }
}
