//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopkeeperStore.EF.Models.Store
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoppingCartDelivery
    {
        public long Id { get; set; }
        public long ShoppingCartId { get; set; }
        public long DeliveredById { get; set; }
        public int DelievryMethodId { get; set; }
        public System.DateTime ExpectedDeliveryDate { get; set; }
        public System.DateTime ActualDateDelivered { get; set; }
        public Nullable<long> DeliveryVesselId { get; set; }
    
        public virtual DeliveryMethod DeliveryMethod { get; set; }
        public virtual DeliveryVessel DeliveryVessel { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual ShoppingCart ShoppingCart { get; set; }
    }
}
