//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopkeeperStore.EF.Models.Store
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoppingCart
    {
        public ShoppingCart()
        {
            this.ShopingCartItems = new HashSet<ShopingCartItem>();
            this.ShoppingCartDeliveries = new HashSet<ShoppingCartDelivery>();
            this.ShoppingCartInvoices = new HashSet<ShoppingCartInvoice>();
        }
    
        public long ShoppingCartId { get; set; }
        public Nullable<long> CustomerId { get; set; }
        public int DeliveryStatus { get; set; }
        public string CustomerIpAddress { get; set; }
        public Nullable<long> DeliveryAddressId { get; set; }
        public System.DateTime DateInitiated { get; set; }
        public Nullable<System.DateTime> DateDelivered { get; set; }
        public Nullable<long> CouponId { get; set; }
    
        public virtual Coupon Coupon { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual DeliveryAddress DeliveryAddress { get; set; }
        public virtual ICollection<ShopingCartItem> ShopingCartItems { get; set; }
        public virtual ICollection<ShoppingCartDelivery> ShoppingCartDeliveries { get; set; }
        public virtual ICollection<ShoppingCartInvoice> ShoppingCartInvoices { get; set; }
    }
}
