//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopkeeperStore.EF.Models.Store
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ShopKeeperStoreEntities : DbContext
    {
        public ShopKeeperStoreEntities()
            : base("name=ShopKeeperStoreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AccountGroup> AccountGroups { get; set; }
        public virtual DbSet<AddressType> AddressTypes { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<BankAccount> BankAccounts { get; set; }
        public virtual DbSet<ChartOfAccount> ChartOfAccounts { get; set; }
        public virtual DbSet<ChildMenu> ChildMenus { get; set; }
        public virtual DbSet<ChildMenuRole> ChildMenuRoles { get; set; }
        public virtual DbSet<ContactType> ContactTypes { get; set; }
        public virtual DbSet<Coupon> Coupons { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<CustomerInvoice> CustomerInvoices { get; set; }
        public virtual DbSet<DailyInventory> DailyInventories { get; set; }
        public virtual DbSet<DailySale> DailySales { get; set; }
        public virtual DbSet<Delivery> Deliveries { get; set; }
        public virtual DbSet<DeliveryAddress> DeliveryAddresses { get; set; }
        public virtual DbSet<DeliveryMethod> DeliveryMethods { get; set; }
        public virtual DbSet<DeliveryVessel> DeliveryVessels { get; set; }
        public virtual DbSet<DocumentType> DocumentTypes { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<EmployeeAssigment> EmployeeAssigments { get; set; }
        public virtual DbSet<EmployeeDocument> EmployeeDocuments { get; set; }
        public virtual DbSet<EmployeeSalesLog> EmployeeSalesLogs { get; set; }
        public virtual DbSet<Estimate> Estimates { get; set; }
        public virtual DbSet<EstimateItem> EstimateItems { get; set; }
        public virtual DbSet<ImageView> ImageViews { get; set; }
        public virtual DbSet<Invoice> Invoices { get; set; }
        public virtual DbSet<InvoiceRequest> InvoiceRequests { get; set; }
        public virtual DbSet<InvoiceRequestItem> InvoiceRequestItems { get; set; }
        public virtual DbSet<IssueType> IssueTypes { get; set; }
        public virtual DbSet<ItemPrice> ItemPrices { get; set; }
        public virtual DbSet<ItemReview> ItemReviews { get; set; }
        public virtual DbSet<JobRole> JobRoles { get; set; }
        public virtual DbSet<ParentMenu> ParentMenus { get; set; }
        public virtual DbSet<ParentMenuRole> ParentMenuRoles { get; set; }
        public virtual DbSet<PaymentType> PaymentTypes { get; set; }
        public virtual DbSet<PersonContact> PersonContacts { get; set; }
        public virtual DbSet<PurchaseOrder> PurchaseOrders { get; set; }
        public virtual DbSet<PurchaseOrderItem> PurchaseOrderItems { get; set; }
        public virtual DbSet<PurchaseOrderItemDelivery> PurchaseOrderItemDeliveries { get; set; }
        public virtual DbSet<PurchaseOrderPayment> PurchaseOrderPayments { get; set; }
        public virtual DbSet<RefundNote> RefundNotes { get; set; }
        public virtual DbSet<Register> Registers { get; set; }
        public virtual DbSet<ReturnedProduct> ReturnedProducts { get; set; }
        public virtual DbSet<Sale> Sales { get; set; }
        public virtual DbSet<SalePayment> SalePayments { get; set; }
        public virtual DbSet<SaleTransaction> SaleTransactions { get; set; }
        public virtual DbSet<Salutation> Salutations { get; set; }
        public virtual DbSet<schema_info> schema_info { get; set; }
        public virtual DbSet<scope_config> scope_config { get; set; }
        public virtual DbSet<scope_info> scope_info { get; set; }
        public virtual DbSet<ShopingCartItem> ShopingCartItems { get; set; }
        public virtual DbSet<ShoppingCart> ShoppingCarts { get; set; }
        public virtual DbSet<ShoppingCartDelivery> ShoppingCartDeliveries { get; set; }
        public virtual DbSet<ShoppingCartInvoice> ShoppingCartInvoices { get; set; }
        public virtual DbSet<StockUpload> StockUploads { get; set; }
        public virtual DbSet<StoreAddress> StoreAddresses { get; set; }
        public virtual DbSet<StoreBank> StoreBanks { get; set; }
        public virtual DbSet<StoreCity> StoreCities { get; set; }
        public virtual DbSet<StoreContact> StoreContacts { get; set; }
        public virtual DbSet<StoreContactTag> StoreContactTags { get; set; }
        public virtual DbSet<StoreCountry> StoreCountries { get; set; }
        public virtual DbSet<StoreCurrency> StoreCurrencies { get; set; }
        public virtual DbSet<StoreCustomerType> StoreCustomerTypes { get; set; }
        public virtual DbSet<StoreDepartment> StoreDepartments { get; set; }
        public virtual DbSet<StoreItem> StoreItems { get; set; }
        public virtual DbSet<StoreItemBrand> StoreItemBrands { get; set; }
        public virtual DbSet<StoreItemCategory> StoreItemCategories { get; set; }
        public virtual DbSet<StoreItemIssue> StoreItemIssues { get; set; }
        public virtual DbSet<StoreItemSold> StoreItemSolds { get; set; }
        public virtual DbSet<StoreItemStock> StoreItemStocks { get; set; }
        public virtual DbSet<StoreItemSupplier> StoreItemSuppliers { get; set; }
        public virtual DbSet<StoreItemType> StoreItemTypes { get; set; }
        public virtual DbSet<StoreItemVariation> StoreItemVariations { get; set; }
        public virtual DbSet<StoreItemVariation_tracking> StoreItemVariation_tracking { get; set; }
        public virtual DbSet<StoreItemVariationValue> StoreItemVariationValues { get; set; }
        public virtual DbSet<StoreMessage> StoreMessages { get; set; }
        public virtual DbSet<StoreMessageTemplate> StoreMessageTemplates { get; set; }
        public virtual DbSet<StoreOutlet> StoreOutlets { get; set; }
        public virtual DbSet<StoreOutletCoupon> StoreOutletCoupons { get; set; }
        public virtual DbSet<StorePaymentGateway> StorePaymentGateways { get; set; }
        public virtual DbSet<StorePaymentMethod> StorePaymentMethods { get; set; }
        public virtual DbSet<StoreSetting> StoreSettings { get; set; }
        public virtual DbSet<StoreState> StoreStates { get; set; }
        public virtual DbSet<StoreTransaction> StoreTransactions { get; set; }
        public virtual DbSet<StoreTransactionType> StoreTransactionTypes { get; set; }
        public virtual DbSet<SubscriptionSetting> SubscriptionSettings { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<SupplierAddress> SupplierAddresses { get; set; }
        public virtual DbSet<TransferNote> TransferNotes { get; set; }
        public virtual DbSet<TransferNoteItem> TransferNoteItems { get; set; }
        public virtual DbSet<UnitsOfMeasurement> UnitsOfMeasurements { get; set; }
        public virtual DbSet<UserProfile> UserProfiles { get; set; }
        public virtual DbSet<Warehouse> Warehouses { get; set; }
        public virtual DbSet<WayBill> WayBills { get; set; }
        public virtual DbSet<WayBillItem> WayBillItems { get; set; }
    }
}
