//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopkeeperStore.EF.Models.Store
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoppingCartInvoice
    {
        public long Id { get; set; }
        public long ShoppingCartId { get; set; }
        public int PaymentStatus { get; set; }
        public string PaymentReference { get; set; }
        public double AmountDue { get; set; }
        public Nullable<double> AmountPaid { get; set; }
        public int PaymentTypeId { get; set; }
        public Nullable<System.DateTime> DatePaid { get; set; }
        public System.DateTime DateGenerated { get; set; }
    
        public virtual ShoppingCart ShoppingCart { get; set; }
    }
}
