//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopkeeperStore.EF.Models.Store
{
    using System;
    using System.Collections.Generic;
    
    public partial class StorePaymentMethod
    {
        public StorePaymentMethod()
        {
            this.RefundNotes = new HashSet<RefundNote>();
            this.StoreTransactions = new HashSet<StoreTransaction>();
        }
    
        public int StorePaymentMethodId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<RefundNote> RefundNotes { get; set; }
        public virtual ICollection<StoreTransaction> StoreTransactions { get; set; }
    }
}
