//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopkeeperStore.EF.Models.Store
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreCustomerType
    {
        public StoreCustomerType()
        {
            this.Customers = new HashSet<Customer>();
        }
    
        public int StoreCustomerTypeId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool CreditWorthy { get; set; }
        public double CreditLimit { get; set; }
    
        public virtual ICollection<Customer> Customers { get; set; }
    }
}
