//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopkeeperStore.EF.Models.Store
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreContact
    {
        public long StoreContactId { get; set; }
        public long PersonId { get; set; }
        public long StoreDepartmentId { get; set; }
        public string DateCreated { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
        public virtual StoreDepartment StoreDepartment { get; set; }
    }
}
