//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopkeeperStore.EF.Models.Store
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreState
    {
        public StoreState()
        {
            this.StoreCities = new HashSet<StoreCity>();
        }
    
        public long StoreStateId { get; set; }
        public string Name { get; set; }
        public long StoreCountryId { get; set; }
    
        public virtual ICollection<StoreCity> StoreCities { get; set; }
        public virtual StoreCountry StoreCountry { get; set; }
    }
}
