//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopkeeperStore.EF.Models.Store
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreItemIssue
    {
        public long StoreItemIssueId { get; set; }
        public long StoreItemStockId { get; set; }
        public int IssueTypeId { get; set; }
        public string Reason { get; set; }
        public System.DateTime IssueDate { get; set; }
        public int ResolutionStatus { get; set; }
    
        public virtual IssueType IssueType { get; set; }
        public virtual StoreItemStock StoreItemStock { get; set; }
    }
}
