//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopkeeperStore.EF.Models.Store
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreItem
    {
        public StoreItem()
        {
            this.StoreItemStocks = new HashSet<StoreItemStock>();
            this.StoreItemSuppliers = new HashSet<StoreItemSupplier>();
            this.WayBillItems = new HashSet<WayBillItem>();
        }
    
        public long StoreItemId { get; set; }
        public long StoreItemBrandId { get; set; }
        public long StoreItemTypeId { get; set; }
        public long StoreItemCategoryId { get; set; }
        public Nullable<int> ChartOfAccountId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<long> ParentItemId { get; set; }
        public string TechSpechs { get; set; }
    
        public virtual ChartOfAccount ChartOfAccount { get; set; }
        public virtual StoreItemBrand StoreItemBrand { get; set; }
        public virtual StoreItemCategory StoreItemCategory { get; set; }
        public virtual StoreItemType StoreItemType { get; set; }
        public virtual ICollection<StoreItemStock> StoreItemStocks { get; set; }
        public virtual ICollection<StoreItemSupplier> StoreItemSuppliers { get; set; }
        public virtual ICollection<WayBillItem> WayBillItems { get; set; }
    }
}
