//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopkeeperStore.EF.Models.Store
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreAddress
    {
        public StoreAddress()
        {
            this.StoreOutlets = new HashSet<StoreOutlet>();
            this.SupplierAddresses = new HashSet<SupplierAddress>();
            this.Warehouses = new HashSet<Warehouse>();
        }
    
        public long StoreAddressId { get; set; }
        public string StreetNo { get; set; }
        public long StoreCityId { get; set; }
    
        public virtual StoreCity StoreCity { get; set; }
        public virtual ICollection<StoreOutlet> StoreOutlets { get; set; }
        public virtual ICollection<SupplierAddress> SupplierAddresses { get; set; }
        public virtual ICollection<Warehouse> Warehouses { get; set; }
    }
}
