//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopkeeperStore.EF.Models.Store
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreSetting
    {
        public int Id { get; set; }
        public string StoreName { get; set; }
        public string StoreAlias { get; set; }
        public string CompanyName { get; set; }
        public string StoreEmail { get; set; }
        public string StoreLogoPath { get; set; }
        public string DefaultCurrency { get; set; }
        public double VAT { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<System.DateTime> DbSyncTimeShedule { get; set; }
        public bool DeductStockAtSalesPoint { get; set; }
        public string Slogan { get; set; }
    }
}
