//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopkeeperStore.EF.Models.Store
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreItemSupplier
    {
        public long SupplierId { get; set; }
        public long StoreItemId { get; set; }
        public int MinSupplyQuantity { get; set; }
        public int MaxSupplyQuantity { get; set; }
        public Nullable<int> UnitOfMeasurement { get; set; }
        public Nullable<double> Rating { get; set; }
        public string StandardPrice { get; set; }
        public double ApplicableDiscount { get; set; }
        public string Comment { get; set; }
    
        public virtual StoreItem StoreItem { get; set; }
    }
}
