//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopkeeperStore.EF.Models.Store
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreItemSold
    {
        public StoreItemSold()
        {
            this.InvoiceRequestItems = new HashSet<InvoiceRequestItem>();
        }
    
        public long StoreItemSoldId { get; set; }
        public long StoreItemStockId { get; set; }
        public long SaleId { get; set; }
        public double QuantitySold { get; set; }
        public double AmountSold { get; set; }
        public int UoMId { get; set; }
        public System.DateTime DateSold { get; set; }
        public double QuantityDelivered { get; set; }
        public double QuantityBalance { get; set; }
        public double Rate { get; set; }
        public double QuantityReturned { get; set; }
    
        public virtual ICollection<InvoiceRequestItem> InvoiceRequestItems { get; set; }
        public virtual Sale Sale { get; set; }
        public virtual StoreItemStock StoreItemStock { get; set; }
    }
}
