//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopkeeperStore.EF.Models.Store
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreItemVariation
    {
        public StoreItemVariation()
        {
            this.StoreItemStocks = new HashSet<StoreItemStock>();
        }
    
        public int StoreItemVariationId { get; set; }
        public string VariationProperty { get; set; }
    
        public virtual ICollection<StoreItemStock> StoreItemStocks { get; set; }
    }
}
