//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopkeeperStore.EF.Models.Store
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreCity
    {
        public StoreCity()
        {
            this.DeliveryAddresses = new HashSet<DeliveryAddress>();
            this.StoreAddresses = new HashSet<StoreAddress>();
        }
    
        public long StoreCityId { get; set; }
        public string Name { get; set; }
        public long StoreStateId { get; set; }
    
        public virtual ICollection<DeliveryAddress> DeliveryAddresses { get; set; }
        public virtual ICollection<StoreAddress> StoreAddresses { get; set; }
        public virtual StoreState StoreState { get; set; }
    }
}
