//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopkeeperStore.EF.Models.Store
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreOutletCoupon
    {
        public long StoreOutletCouponId { get; set; }
        public int StoreOutletId { get; set; }
        public long CouponId { get; set; }
    
        public virtual Coupon Coupon { get; set; }
        public virtual StoreOutlet StoreOutlet { get; set; }
    }
}
