//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopkeeperStore.EF.Models.Store
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreOutlet
    {
        public StoreOutlet()
        {
            this.Customers = new HashSet<Customer>();
            this.DailySales = new HashSet<DailySale>();
            this.Employees = new HashSet<Employee>();
            this.EmployeeAssigments = new HashSet<EmployeeAssigment>();
            this.Estimates = new HashSet<Estimate>();
            this.PurchaseOrders = new HashSet<PurchaseOrder>();
            this.Registers = new HashSet<Register>();
            this.StoreItemStocks = new HashSet<StoreItemStock>();
            this.StoreOutletCoupons = new HashSet<StoreOutletCoupon>();
            this.StoreTransactions = new HashSet<StoreTransaction>();
            this.TransferNotes = new HashSet<TransferNote>();
            this.TransferNotes1 = new HashSet<TransferNote>();
        }
    
        public int StoreOutletId { get; set; }
        public string OutletName { get; set; }
        public long StoreAddressId { get; set; }
        public bool IsMainOutlet { get; set; }
        public Nullable<double> DefaultTax { get; set; }
        public bool IsOperational { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string FacebookHandle { get; set; }
        public string TwitterHandle { get; set; }
    
        public virtual ICollection<Customer> Customers { get; set; }
        public virtual ICollection<DailySale> DailySales { get; set; }
        public virtual ICollection<Employee> Employees { get; set; }
        public virtual ICollection<EmployeeAssigment> EmployeeAssigments { get; set; }
        public virtual ICollection<Estimate> Estimates { get; set; }
        public virtual ICollection<PurchaseOrder> PurchaseOrders { get; set; }
        public virtual ICollection<Register> Registers { get; set; }
        public virtual StoreAddress StoreAddress { get; set; }
        public virtual ICollection<StoreItemStock> StoreItemStocks { get; set; }
        public virtual ICollection<StoreOutletCoupon> StoreOutletCoupons { get; set; }
        public virtual ICollection<StoreTransaction> StoreTransactions { get; set; }
        public virtual ICollection<TransferNote> TransferNotes { get; set; }
        public virtual ICollection<TransferNote> TransferNotes1 { get; set; }
    }
}
