//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopkeeperStore.EF.Models.Store
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierAddress
    {
        public long SupplierAddressId { get; set; }
        public long SupplierId { get; set; }
        public long StoreAddressId { get; set; }
        public System.DateTime DateFrom { get; set; }
        public System.DateTime DateTo { get; set; }
        public int AddressTypeId { get; set; }
    
        public virtual AddressType AddressType { get; set; }
        public virtual StoreAddress StoreAddress { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
