//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopkeeperStore.EF.Models.Store
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransferNoteItem
    {
        public long Id { get; set; }
        public long TransferNoteId { get; set; }
        public double TotalQuantityRaised { get; set; }
        public double TotalQuantityTransfered { get; set; }
        public double TotalAmountRaised { get; set; }
        public double TotalAmountTransfered { get; set; }
        public double Rate { get; set; }
        public long StoreItemStockId { get; set; }
        public Nullable<System.DateTime> DateTransferd { get; set; }
        public long UoMId { get; set; }
    
        public virtual StoreItemStock StoreItemStock { get; set; }
        public virtual TransferNote TransferNote { get; set; }
        public virtual UnitsOfMeasurement UnitsOfMeasurement { get; set; }
    }
}
