//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopkeeperStore.EF.Models.Store
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransferNote
    {
        public TransferNote()
        {
            this.TransferNoteItems = new HashSet<TransferNoteItem>();
        }
    
        public long Id { get; set; }
        public double TotalAmount { get; set; }
        public System.DateTime DateGenerated { get; set; }
        public long GeneratedByUserId { get; set; }
        public int SourceOutletId { get; set; }
        public int TargetOutletId { get; set; }
        public int Status { get; set; }
        public Nullable<System.DateTime> DateTransferd { get; set; }
        public string TransferNoteNumber { get; set; }
    
        public virtual StoreOutlet StoreOutlet { get; set; }
        public virtual StoreOutlet StoreOutlet1 { get; set; }
        public virtual UserProfile UserProfile { get; set; }
        public virtual ICollection<TransferNoteItem> TransferNoteItems { get; set; }
    }
}
