//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopkeeperStore.EF.Models.Store
{
    using System;
    using System.Collections.Generic;
    
    public partial class Warehouse
    {
        public long WarehouseId { get; set; }
        public string Name { get; set; }
        public long StoreAddressId { get; set; }
        public long CompanyId { get; set; }
    
        public virtual StoreAddress StoreAddress { get; set; }
    }
}
