//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopkeeperStore.EF.Models.Store
{
    using System;
    using System.Collections.Generic;
    
    public partial class WayBill
    {
        public WayBill()
        {
            this.WayBillItems = new HashSet<WayBillItem>();
        }
    
        public long WayBillId { get; set; }
        public long AuthorisedById { get; set; }
        public long SourceId { get; set; }
        public long DeliveryId { get; set; }
        public int TotalItems { get; set; }
        public System.DateTime DatePacked { get; set; }
        public long PackedById { get; set; }
        public long CheckedById { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual ICollection<WayBillItem> WayBillItems { get; set; }
    }
}
